# Site settings
title: Ilya Shaisultanov
description: "When 140 characters isn't enough."
url: 'http://diversario.github.io/'
baseurl: '/'
google_analytics: 'UA-51511945-2'

author:
  name: 'Ilya Shaisultanov'
  email: ilya.shaisultanov@gmail.com
  twitter_username: diversario
  github_username:  diversario
  linkedin_username:  shaisultanov

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
